/**
 * Códigos de error canónicos del API.
 * Fuente: BackendArchitecture.md §19 "Códigos de Error Canónicos".
 * Compartido entre backend (los emite) y mobile (los interpreta para UI).
 */
export enum ErrorCode {
  // Autenticación
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  ACCOUNT_DELETED = 'ACCOUNT_DELETED',

  // Autorización
  FORBIDDEN = 'FORBIDDEN',
  PREMIUM_REQUIRED = 'PREMIUM_REQUIRED',
  ONBOARDING_REQUIRED = 'ONBOARDING_REQUIRED',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',

  // Validación
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  WEAK_PASSWORD = 'WEAK_PASSWORD',
  TERMS_NOT_ACCEPTED = 'TERMS_NOT_ACCEPTED',

  // Rate limiting
  DAILY_LIMIT_REACHED = 'DAILY_LIMIT_REACHED',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // Negocio
  ACTIVE_SESSION_EXISTS = 'ACTIVE_SESSION_EXISTS',
  ASSESSMENT_REQUIRED = 'ASSESSMENT_REQUIRED',
  INVALID_SYNC_PLATFORM = 'INVALID_SYNC_PLATFORM',

  // Servicios externos
  AI_UNAVAILABLE = 'AI_UNAVAILABLE',
  FOOD_DB_UNAVAILABLE = 'FOOD_DB_UNAVAILABLE',
  UPLOAD_FAILED = 'UPLOAD_FAILED',

  // Servidor
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  REQUEST_TIMEOUT = 'REQUEST_TIMEOUT',
}
